project/project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^sentiment/', include('sentiment.urls', namespace='sentiment')),
    url(r'^admin/', include(admin.site.urls)),
]

project/sentiment/urls.py
from django.conf.urls import url
from sentiment.views import IndexView, BarChartView, SecondView, LineChartView, TweetView, ThirdView, DotChartView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^bar_chart$', BarChartView.as_view(), name='bar_chart'),
    url(r'^second$', SecondView.as_view(),name="second" ),
    url(r'^line_chart$', LineChartView.as_view(), name='line_chart'),
    url(r'^tweet', TweetView.as_view(), name='tweet'),
    url(r'^third$', ThirdView.as_view(),name="third" ),
    url(r'^dot_chart$', DotChartView.as_view(), name='dot_chart'),


]

project/sentiment/models.py
from django.db import models

class Tweet(models.Model):
    text = models.CharField(max_length=200)
    date = models.DateTimeField()
    query_string = models.CharField(max_length=200)
    candidate = models.CharField(max_length=200)
    score = models.DecimalField(max_digits=6, decimal_places=5, default=0.5)

class Word(models.Model):
	word = models.CharField(max_length=150,db_index=True)
	positive = models.IntegerField()
	negative = models.IntegerField()

project/sentiment/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from sentiment.models import Tweet, Word
from sentiment.bayes import *
from django.db.models import Avg
from django.http import JsonResponse



class IndexView(View):
    template = 'sentiment/index.html'
    def get(self, request):
        return render(request, self.template)


class BarChartView(View):
	candidate_list = ["Trump", "Bush", "Walker", "Huckabee", "Carson", "Cruz", "Rubio", "Paul", "Christie", "Kasich"]

	def get(self,request):
		candidate_dict = {}
		for candidate in self.candidate_list:
			score = Tweet.objects.filter(candidate = candidate).aggregate(Avg('score'))
			candidate_dict[candidate] = score
		return JsonResponse({"candidates":candidate_dict})


class SecondView(View):
    template = 'sentiment/second.html'
    candidate_list = ["Trump", "Bush", "Walker", "Huckabee", "Carson", "Cruz", "Rubio", "Paul", "Christie", "Kasich"]

    def get(self, request):
        return render(request, self.template, {'candidates': self.candidate_list})



class LineChartView(View):
	candidate_list = ["Trump", "Bush", "Walker", "Huckabee", "Carson", "Cruz", "Rubio", "Paul", "Christie", "Kasich"]

	def get(self,request):
		candidate_dict = {}
		for candidate in self.candidate_list:
			tweets = Tweet.objects.filter(candidate = candidate)
			### Create list of all times
			tweet_time_list = {}
			for hours in range(0,4):
				for minutes in range(0,60):
					tweet_time_list[hours*60+minutes] = []
			### Assigns all tweets to a time in the time_list
			for tweet in tweets:
				for time in tweet_time_list:
					if tweet.date.hour * 60 + tweet.date.minute == time:
						tweet_time_list[time].append(tweet)
			## Calculates rolling average
			rolling_average_list = {}
			for x in range(6,4*60):
				score = 0
				length = 0
				for y in range(x-5,x+1):
					tweets = tweet_time_list[y]
					for tweet in tweets:
						length += 1
						score += tweet.score
				if length > 0:
					rolling_average = score / length
					rolling_average_list[x] = rolling_average
			candidate_dict[candidate] = rolling_average_list
		return JsonResponse({"candidates":candidate_dict})
       	
class TweetView(View):

	def get(self, request):
		print('in tweet')
		time = int(float(request.GET.get('time')))
		candidate = request.GET.get('candidate')
		rating = float(request.GET.get('rating'))
		# print(time)
		tweets = Tweet.objects.filter(candidate=candidate)
		# print(tweets.count())
		# print(tweets[0].date)
		# print(tweets[0].date.hour)
		# print(tweets[0].date.minute)
		for tweet in tweets:
			print(time)
			print(tweet.date.hour * 60 + tweet.date.minute)
			if tweet.date.hour * 60 + tweet.date.minute in range(time-5,time+5) and rating -0.05 < tweet.score < rating + 0.05 :
				return JsonResponse({"tweet": tweet.text, "score": tweet.score, "date": tweet.date})
		return JsonResponse({"tweet": "No Tweet found"})


class ThirdView(View):
    template = 'sentiment/third.html'
    candidate_list = ["Trump", "Bush", "Walker", "Huckabee", "Carson", "Cruz", "Rubio", "Paul", "Christie", "Kasich"]

    def get(self, request):
        return render(request, self.template, {'candidates': self.candidate_list})


class DotChartView(View):

	def get(self,request):
		all_tweets = Tweet.objects.all()
		list_tweets = []
		for tweet in all_tweets:
			time = tweet.date.hour * 60 + tweet.date.minute 
			list_tweets.append({"text":tweet.text, "time":time,"score":tweet.score,"candidate":tweet.candidate})

		return JsonResponse({"all_tweets":list_tweets})

  

project/sentiment/templates/sentiment/index.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <title></title>
<link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="http://d3js.org/d3.v3.min.js"></script>
<link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="http://getbootstrap.com/examples/justified-nav/justified-nav.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href ="{% static 'sentiment/main.css' %}">
<script src="{% static 'sentiment/front_end.js' %}"> </script>
</head>
<body>
<div>
    <div id="bar_chart"> </div>
    <div class="nav" style ="margin-left: 55em">
        <a href="{% url 'sentiment:second' %}">Next</a>
    </div>
</div>
</body>

</html>

project/sentiment/templates/sentiment/line_chart.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <title></title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="http://d3js.org/d3.v3.min.js"></script>
<link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="http://getbootstrap.com/examples/justified-nav/justified-nav.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href ="{% static 'sentiment/main.css' %}">
<script src="{% static 'sentiment/line_chart.js' %}"> </script>
</head>
<body>

<div id="line_chart"> </div>

</body>

</html>

project/sentiment/templates/sentiment/second.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <title></title>
<link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="http://d3js.org/d3.v3.min.js"></script>
<link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="http://getbootstrap.com/examples/justified-nav/justified-nav.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href ="{% static 'sentiment/main.css' %}">
<script src="{% static 'sentiment/line_chart.js' %}"> </script>
</head>
 
<body>
    <div class="container">
        <div class="jumbotron">
            <svg id="visualisation" width="1000" height="500"></svg>
        </div>
    </div> 
    <div id = "tweet" style ="width:800px; margin:0 auto"></div>
    <div id ="buttons" style ="width:800px; margin:0 auto">
        {%if candidates%}
            {%for candidate in candidates%}
                <button class="btn btn-primary candidate_buttons" id="{{candidate}}">{{ candidate }}</button>
            {%endfor%}
        {%endif%}
    </div>
    <div class = "nav" style ="width:220px; margin:0 auto">
        <a href="{% url 'sentiment:index' %}">Back</a>
        <a href="{% url 'sentiment:third' %}">Next</a>
    </div>

</body>
 
</html>

project/sentiment/templates/sentiment/third.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <title></title>
<link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="http://d3js.org/d3.v3.min.js"></script>
<link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="http://getbootstrap.com/examples/justified-nav/justified-nav.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href ="{% static 'sentiment/main.css' %}">
<script src="{% static 'sentiment/dot_chart.js' %}"> </script>
</head>
 
<body>
    
<div id="tweet" width ="20em"></div>
<div class = "nav">
    <a href="{% url 'sentiment:second' %}">Back</a>
</div>


</body>
 
</html>